--liquibase formatted sql

--changeset isolomin:1
CREATE TABLE IF NOT EXISTS transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id UUID NOT NULL,
    operation_type CHARACTER VARYING(255) NOT NULL,
    amount DECIMAL NOT NULL,
    status CHARACTER VARYING(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
)

--changeset isolomin:2
CREATE INDEX idx_transfer_wallet_id ON transfer (wallet_id);